// GENERATED by scripts/appwrite/sync-analytics-allowlists.js. Do not edit by hand.
// Sources: src/seo/routeRegistry.js (analyticsPaths), src/v4/analytics/campaigns.js and src/v4/analytics/dimensions.js.

export const NOT_FOUND_PATH = "/404/";

export const KNOWN_PATHS = [
  "/",
  "/404/",
  "/about/",
  "/book/",
  "/case-studies/",
  "/checkout/cancel/",
  "/checkout/success/",
  "/company/about/",
  "/contact/",
  "/diagnostic/",
  "/faq/",
  "/legal/cookies/",
  "/legal/privacy/",
  "/legal/terms/",
  "/platform/",
  "/pricing/",
  "/privacy-policy/",
  "/refund-policy/",
  "/resources/",
  "/resources/aging-ar-playbook/",
  "/resources/credentialing-operations-checklist/",
  "/resources/denial-management-root-cause/",
  "/resources/healthcare-automation-readiness/",
  "/resources/practice-ops-kpi-model/",
  "/resources/revenue-leakage-guide/",
  "/services/",
  "/services/ar-recovery/",
  "/services/credentialing/",
  "/services/denial-management/",
  "/services/healthcare-it/",
  "/services/medical-billing/",
  "/services/operational-consulting/",
  "/services/patient-balances/",
  "/services/payment-posting/",
  "/services/practice-ops/",
  "/services/rcm/",
  "/services/reporting-analytics/",
  "/services/workflow-automation/",
  "/solutions/",
  "/solutions/aging-ar/",
  "/solutions/credentialing-bottlenecks/",
  "/solutions/denials/",
  "/solutions/operational-efficiency/",
  "/solutions/reporting-visibility/",
  "/solutions/revenue-leakage/",
  "/solutions/scaling-practice-ops/",
  "/technology/",
  "/technology/dirt/",
  "/terms/",
  "/thank-you/"
];

export const UTM_SOURCES = [
  "bing",
  "direct",
  "duckduckgo",
  "email",
  "facebook",
  "google",
  "instagram",
  "linkedin",
  "newsletter",
  "partner",
  "pinterest",
  "qr",
  "reddit",
  "referral",
  "twitter",
  "x",
  "youtube"
];

export const UTM_MEDIUMS = [
  "affiliate",
  "cpc",
  "display",
  "email",
  "newsletter",
  "organic",
  "paid",
  "partner",
  "ppc",
  "print",
  "qr",
  "referral",
  "social"
];

export const UTM_CAMPAIGNS = [];

export const CTA_IDS = [
  "book-conversation",
  "book-diagnostic",
  "compare-pricing",
  "email-root",
  "engagement-row",
  "explore-dirt",
  "intent-banner",
  "open-email",
  "phone-call",
  "pricing-card",
  "related-solution",
  "request-diagnostic",
  "return-home",
  "schedule-call",
  "social-click",
  "start-checkout",
  "start-conversation",
  "talk-to-root",
  "talk-to-us-open",
  "view-services",
  "whatsapp-instant-chat"
];

export const CTA_LOCATIONS = [
  "404",
  "book-page",
  "book-page-outreach",
  "campaign-diagnostic",
  "checkout-cancel",
  "checkout-success",
  "contact-form",
  "contact-form-fallback",
  "contact-page-outreach",
  "diagnostic-form",
  "diagnostic-form-fallback",
  "diagnostic-hero",
  "dirt-diagnostic",
  "dirt-hero",
  "exit-diagnostic",
  "faq",
  "floating-contact",
  "follow-panel",
  "follow-root",
  "footer",
  "footer-contact",
  "footer-outreach",
  "footer-social",
  "header",
  "home-capabilities",
  "home-diagnostic-preview",
  "home-dirt",
  "home-final-cta",
  "home-hero",
  "home-operating-model",
  "home-outreach",
  "home-pricing",
  "mobile-nav",
  "page",
  "page-hero",
  "platform-engagement",
  "platform-hero",
  "pricing-core",
  "pricing-diagnostic",
  "pricing-featured",
  "pricing-mobile",
  "pricing-specialized",
  "pricing-table",
  "resource-proof",
  "returning",
  "service-ar-recovery",
  "service-credentialing",
  "service-denial-management",
  "service-healthcare-it",
  "service-medical-billing",
  "service-operational-consulting",
  "service-patient-balances",
  "service-payment-posting",
  "service-practice-ops",
  "service-rcm",
  "service-reporting-analytics",
  "service-workflow-automation",
  "talk-to-us",
  "talk-to-us-dialog",
  "thank-you"
];

export const ENGAGEMENT_TYPES = [
  "checkout",
  "consultation",
  "contact",
  "credentialing",
  "diagnostic",
  "dirt-data-intelligence",
  "email",
  "full-mso-partnership",
  "instant-chat",
  "managed-rcm",
  "navigation",
  "phone",
  "pricing",
  "projects-automation",
  "scheduling",
  "services",
  "social",
  "solution",
  "technology"
];

export const FORM_IDS = [
  "book-inquiry",
  "contact-inquiry",
  "diagnostic-inquiry"
];

export const STATUSES = [
  "failure",
  "paid",
  "success"
];

export const PRODUCT_IDS = [
  "revenue-optimization-diagnostic"
];

export const DESTINATION_LABELS = [
  "Call",
  "Email",
  "Facebook",
  "Instagram",
  "LinkedIn",
  "Pinterest",
  "Reddit",
  "WhatsApp",
  "X",
  "stripe-checkout"
];

export const EXPERIMENT_VARIANTS = {
  "exp-checkout-cta-v1": [
    "control",
    "start-now"
  ],
  "exp-follow-us-design-v1": [
    "control",
    "labeled"
  ],
  "exp-header-cta-v1": [
    "control",
    "explore"
  ],
  "exp-hero-cta-v1": [
    "control",
    "fixed-fee"
  ],
  "exp-pricing-presentation-v1": [
    "at-a-glance",
    "control"
  ],
  "exp-talk-to-us-placement-v1": [
    "control",
    "footer-only"
  ]
};
