export const syntheticPractice = {
  name: 'Willowbend Physician Group',
  label: 'Synthetic demonstration practice',
  specialty: 'Independent primary care and adult medicine',
  providers: 5,
  period: 'Illustrative 90-day operating view',
  monthlyCharges: 1120000,
  monthlyCollections: 842000,
  contractualAdjustments: 198000,
  totalAr: 780000,
  arOver90: 265000,
  cleanClaimRate: '86.4%',
  denialRate: '11.8%',
  payerMix: [
    ['Commercial', 45],
    ['Medicare', 28],
    ['Medicaid', 16],
    ['Self-pay', 7],
    ['Other', 4],
  ],
};

export const proofWorkAssets = {
  rcmControl: {
    title: 'Revenue-cycle KPI control view',
    label: 'Synthetic demonstration',
    capability: 'RCM operating controls',
    seeing: 'Charges, collections, denials, clean-claim quality, and active follow-up in one control view.',
    meaning: 'Leadership can see whether the revenue engine is controlled or simply busy.',
    action: 'Tighten queue ownership, review cadence, payer follow-up, and exception escalation.',
    insight: 'Charges, collections, aging, denial rate, clean-claim rate, and queue ownership are shown together so the operating question is clear.',
    metrics: [
      ['Monthly charges', '$1.12M'],
      ['Collections', '$842K'],
      ['Clean claim rate', '86.4%'],
      ['Denial rate', '11.8%'],
    ],
    workflow: [
      ['Charge review', 'Owner: Billing lead', '2 open edits'],
      ['Claim scrub', 'Owner: QA', '18 warnings'],
      ['Submission', 'Owner: Claims', '94% within 48h'],
      ['Payer follow-up', 'Owner: AR team', '$312K active'],
    ],
  },
  arAnalysis: {
    title: 'A/R aging and recovery priority',
    label: 'Illustrative practice data',
    capability: 'A/R recovery analysis',
    seeing: 'Aging buckets, high-value segments, recoverability, payer friction, and next action.',
    meaning: 'A/R is not one backlog; it is several different workflows competing for attention.',
    action: 'Rank recoverable balances by value, owner, payer status, and escalation path.',
    insight: '$780K total A/R reconciles across aging buckets; $265K is over 90 days and is split by recoverability, payer behavior, and next action.',
    buckets: [
      ['0-30', 242000],
      ['31-60', 154000],
      ['61-90', 119000],
      ['91-120', 101000],
      ['120+', 164000],
    ],
    queue: [
      ['Commercial follow-up', '$118K', 'High', 'Payer response overdue'],
      ['Authorization appeal', '$64K', 'High', 'Clinical packet needed'],
      ['Patient responsibility', '$41K', 'Medium', 'Statement cadence'],
      ['Documentation hold', '$42K', 'Medium', 'Provider response'],
    ],
  },
  denialPareto: {
    title: 'Denial root-cause Pareto',
    label: 'Sample analytical output',
    capability: 'Denial management',
    seeing: 'Denial events grouped into cause families with value-at-risk context.',
    meaning: 'Recurring denial categories point to workflow defects, not only claim-level rework.',
    action: 'Recover what is collectible and close the upstream loop on preventable sources.',
    insight: '182 synthetic denial events reconcile to six categories and separate recoverable work from upstream prevention.',
    categories: [
      ['Eligibility', 56, 64000, 'Front-end verification'],
      ['Authorization', 42, 52000, 'Referral and auth workflow'],
      ['Coding edit', 31, 37000, 'Documentation/coding review'],
      ['Medical necessity', 22, 29000, 'Evidence packet'],
      ['Credentialing', 18, 22000, 'Enrollment status'],
      ['Timely filing', 13, 10000, 'Submission control'],
    ],
  },
  credentialingTracker: {
    title: 'Credentialing command view',
    label: 'De-identified workflow example',
    capability: 'Credentialing operations',
    seeing: 'Enrollment status, payer, aging task, owner, and bottleneck in one workflow table.',
    meaning: 'Credentialing delay can become revenue timing risk before leadership sees it in cash.',
    action: 'Assign follow-up ownership, missing-document cleanup, and payer escalation cadence.',
    insight: 'Provider enrollment is managed as a revenue-timing workflow with payer status, missing documents, aging tasks, and escalation owners.',
    rows: [
      ['Dr. Avery Lane', 'Commercial Plus', 'In committee', '18 days', 'Credentialing'],
      ['Dr. Morgan Ellis', 'Medicare', 'Submitted', '26 days', 'Enrollment'],
      ['Nia Patel, PA-C', 'Regional Medicaid', 'Missing roster update', '9 days', 'Practice admin'],
      ['Dr. Rowan Blake', 'Workers Comp', 'Payer follow-up', '34 days', 'Credentialing'],
    ],
  },
  practiceOpsScorecard: {
    title: 'Practice operations scorecard',
    label: 'Representative workflow based on RCM operating experience',
    capability: 'Practice operations',
    seeing: 'Backlog, overdue escalations, posting exceptions, credentialing blockers, and queue priority.',
    meaning: 'Operational drag shows up as revenue-cycle noise unless the workflow is visible.',
    action: 'Create owner-based work queues, leadership cadence, and process cleanup sequence.',
    insight: 'Backlog, ownership, queue aging, and leadership cadence are tied to the same revenue-cycle signal set.',
    metrics: [
      ['Unworked claim actions', '74'],
      ['Overdue escalations', '19'],
      ['Posting exceptions', '11'],
      ['Credentialing blockers', '3'],
    ],
    matrix: [
      ['High value / high urgency', 'AR recovery sprint'],
      ['High value / lower urgency', 'Payer trend review'],
      ['Lower value / high urgency', 'Submission edit cleanup'],
      ['Lower value / lower urgency', 'Report hygiene backlog'],
    ],
  },
  dirtCommand: {
    title: 'DIRT management intelligence view',
    label: 'Demonstration dataset',
    capability: 'DIRT intelligence',
    seeing: 'Revenue leakage, A/R concentration, payer risk, and workflow priority signals.',
    meaning: 'DIRT turns scattered operational exports into management intelligence.',
    action: 'Move from signal to ranked decision, assigned owner, next action, and review rhythm.',
    insight: 'Raw operational signals are converted into ranked management decisions with evidence, owner, and next action.',
    signals: [
      ['Revenue leakage', '$214K value at risk', 'Denials and aging concentration'],
      ['A/R concentration', '$265K over 90', 'Commercial and auth-driven backlog'],
      ['Payer risk', '3 payer groups', 'Payment delay plus denial recurrence'],
      ['Workflow priority', '4 workstreams', 'Owner, cadence, escalation'],
    ],
  },
};

export const diagnosticSample = {
  title: 'Illustrative Revenue Optimization Diagnostic',
  pages: [
    ['Executive summary', 'Five-provider practice, $780K A/R, 34% over 90 days, denial concentration in eligibility and authorization.'],
    ['Revenue leakage map', '$214K synthetic value at risk across denials, payer delay, unresolved A/R, and credentialing exposure.'],
    ['Opportunity register', 'Ranked work queue with owner, evidence, next action, recoverability, and escalation path.'],
    ['30/60/90 roadmap', 'Stabilize work queues, correct denial causes, rebuild KPI cadence, then monitor DIRT signals weekly.'],
  ],
};

export const proofPlacementByServiceSlug = {
  rcm: 'rcmControl',
  'medical-billing': 'rcmControl',
  'ar-recovery': 'arAnalysis',
  'payment-posting': 'rcmControl',
  'patient-balances': 'arAnalysis',
  'denial-management': 'denialPareto',
  credentialing: 'credentialingTracker',
  'practice-ops': 'practiceOpsScorecard',
  'healthcare-it': 'dirtCommand',
  'workflow-automation': 'practiceOpsScorecard',
  'reporting-analytics': 'dirtCommand',
  'operational-consulting': 'practiceOpsScorecard',
};

export const proofPlacementBySolutionSlug = {
  'revenue-leakage': 'dirtCommand',
  'aging-ar': 'arAnalysis',
  denials: 'denialPareto',
  'credentialing-bottlenecks': 'credentialingTracker',
  'operational-efficiency': 'practiceOpsScorecard',
  'reporting-visibility': 'dirtCommand',
  'scaling-practice-ops': 'practiceOpsScorecard',
};

export const proofPlacementByResourceSlug = {
  'revenue-leakage-guide': 'dirtCommand',
  'aging-ar-playbook': 'arAnalysis',
  'denial-management-root-cause': 'denialPareto',
  'credentialing-operations-checklist': 'credentialingTracker',
  'practice-ops-kpi-model': 'practiceOpsScorecard',
  'healthcare-automation-readiness': 'practiceOpsScorecard',
};
